name: Deploy Application to AKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:

  build-deploy:

    runs-on:
      - self-hosted
      - Linux
      - X64

    steps:

      # 1. Checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: 0125ae9e-0326-45f3-8b95-bbf4719b7514
          tenant-id: 6f3dd6ca-22ac-4502-94be-48e8cb061c33
          subscription-id: 5deb291d-199b-4e8c-a522-d3f6f5f9c776

      # 3. Check Azure
      - name: Check Azure Account
        run: |
          az account show

      # 4. Login ACR
      - name: Login to ACR
        run: |
          az acr login --name satishregistry001

      # 5. Docker Check
      - name: Check Docker
        run: |
          docker --version
          docker info

      # 6. Build Image
      - name: Build Docker Image
        run: |
          docker build \
            -t satishregistry001.azurecr.io/axion-ui:${{ github.run_number }} \
            .

      # 7. Push Image
      - name: Push Image to ACR
        run: |
          docker push \
            satishregistry001.azurecr.io/axion-ui:${{ github.run_number }}

      # 8. Verify Image
      - name: Verify Image
        run: |
          az acr repository show-tags \
            --name satishregistry001 \
            --repository axion-ui \
            --output table

      # 9. Install yq
      - name: Install yq
        run: |
          if ! command -v yq >/dev/null 2>&1; then
            sudo wget -qO /usr/local/bin/yq \
              https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq
          fi

          yq --version

      # 10. Show Manifest
      - name: Check Deployment
        run: |
          cat k8s/diployment.yml

      # 11. Update Kubernetes Image
      - name: Update Image Tag
        run: |
          yq e \
            '(.spec.template.spec.containers[] | select(.name == "axion-ui").image) = "satishregistry001.azurecr.io/axion-ui:${{ github.run_number }}"' \
            -i k8s/diployment.yml

          echo "Updated Deployment:"
          cat k8s/diployment.yml

      # 12. Verify Git Diff
      - name: Check Git Changes
        run: |
          git status
          git diff -- k8s/diployment.yml

      # 13. Commit
      - name: Commit Image Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add k8s/diployment.yml

          git commit \
            -m "Update axion-ui image tag to ${{ github.run_number }} [skip ci]" \
            || echo "No changes to commit"

      # 14. Push to GitHub
      - name: Push Git Changes
        run: |
          git push
